# Generated by Django 5.1.7 on 2025-03-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=50)),
                ('author_last_name', models.CharField(max_length=50)),
                ('activate_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activate_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('article', models.TextField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.author')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.subjects')),
            ],
        ),
    ]
