# Generated by Django 5.1.7 on 2025-03-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='activate_status',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='activate_status',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
