# Generated by Django 5.1.7 on 2025-03-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_author_activate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='thumb_image',
            field=models.URLField(default='https://coffective.com/wp-content/uploads/2018/06/default-featured-image.png.jpg'),
        ),
    ]
