# Generated by Django 5.1.7 on 2025-03-22 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_record_thumb_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Categories',
        ),
    ]
